name: Run OctivBookerBot Callable

on:
  workflow_call:
    inputs:
      schedule_label:
        required: false
        type: string
    secrets:
      OCTIV_USERNAME:
        required: true
      OCTIV_PASSWORD:
        required: true
      EMAIL_SENDER:
        required: true
      EMAIL_PASSWORD:
        required: true
      EMAIL_RECEIVER:
        required: true
      EMAIL_RECEIVER_NAME:
        required: true

env:
  DOCKER_IMAGE: "octivbooker:v2.6.3"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      environment_dir_list: ${{ steps.get_envdirs.outputs.environment_dir_list }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List environment subdirectories
        id: get_envdirs
        run: |
          ENV_SUBDIRS=$(find src/slotbooker/data/prod/1900 -type d -maxdepth 1 -mindepth 1 -exec basename {} \;)
          ENV_SUBDIR_LIST=$(echo "$ENV_SUBDIRS" | jq -R -s -c 'split("\n")[:-1]')
          echo "environment_dir_list=$ENV_SUBDIR_LIST" >> $GITHUB_OUTPUT
          echo $ENV_SUBDIR_LIST

  run-octivbooker:
    name: "üèãÔ∏è‚Äç‚ôÇÔ∏è Run OctivBooker ${{ matrix.environment }}"
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ${{ fromJson(needs.prepare.outputs.environment_dir_list) }}
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run OctivBooker Docker Container
        run: |
          docker run --rm \
          --volume $(pwd)/src/slotbooker/data/prod/1900/${{ matrix.environment }}:/app/src/slotbooker/data/ \
          -e OCTIV_USERNAME="${{ secrets.OCTIV_USERNAME }}" \
          -e OCTIV_PASSWORD="${{ secrets.OCTIV_PASSWORD }}" \
          -e EMAIL_SENDER="${{ secrets.EMAIL_SENDER }}" \
          -e EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
          -e EMAIL_RECEIVER="${{ secrets.EMAIL_RECEIVER }}" \
          -e EMAIL_RECEIVER_NAME="${{ secrets.EMAIL_RECEIVER_NAME }}" \
          -e DAYS_BEFORE_BOOKABLE="${{ vars.DAYS_BEFORE_BOOKABLE }}" \
          -e EXECUTION_BOOKING_TIME="${{ vars.EXECUTION_BOOKING_TIME }}" \
          seblum/${{ env.DOCKER_IMAGE }}
